apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flight-app.fullname" . }}-config
  labels:
    {{- include "flight-app.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  RABBITMQ_URL: {{ .Values.env.RABBITMQ_URL | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-app.fullname" . }}-secrets
  labels:
    {{- include "flight-app.labels" . | nindent 4 }}
type: Opaque
data:
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | b64enc | quote }}
