{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flight-app.fullname" . }}
  labels:
    {{- include "flight-app.labels" . | nindent 4 }}
{{- end }}
