{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flight-app.fullname" . }}-worker
  labels:
    {{- include "flight-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flight-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "flight-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "flight-app.fullname" . }}
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["sh", "-c", "{{ .Values.worker.command }}"]
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: {{ include "flight-app.fullname" . }}-config
{{- end }}
