apiVersion: v1
kind: ConfigMap
metadata:
  name: flight-app-config
  labels:
    app.kubernetes.io/name: flight-app
data:
  DATABASE_URL: "postgresql://user:pass@db:5432/flights"
  RABBITMQ_URL: "pyamqp://admin:admin123@rabbitmq:5672//"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
