"""add users table

Revision ID: edac8bdebda8
Revises: 001
Create Date: 2026-03-06 20:50:07.877261

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'edac8bdebda8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.alter_column('flights', 'flight_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flights', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flights', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('flights', 'destination_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.alter_column('flights', 'destination_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('flights', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('flights', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flights', 'flight_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
